# CertWatch Configuration File

log_level = "info"
log_metrics = true

[network]
certstream_url = "wss://127.0.0.1:8181/domains-only"
sample_rate = 1.0
allow_invalid_certs = true

[matching]
# A list of file paths containing regex patterns.
# For example: pattern_files = ["/path/to/your/patterns.txt"]
pattern_files = ["ignored/phishing.txt"]
# pattern_files = ["ignored/phishing.txt", "ignored/dot-top.txt"]

[dns]

# DNS retry and backoff settings.
standard_retries = 3
standard_initial_backoff_ms = 500
nxdomain_retries = 5
nxdomain_initial_backoff_ms = 10000

[dns.health]
# The failure rate threshold to trigger the unhealthy state (e.g., 0.95 for 95%).
failure_threshold = 0.95
# The time window in seconds to consider for the failure rate calculation.
window_seconds = 120
# A known-good domain to resolve to check for recovery.
recovery_check_domain = "google.com"

[enrichment]
# Path to the TSV ASN database file.
# The file must be tab-separated with 5 columns:
# CIDR, AS_Number, AS_Name, Country_Code, Description
# https://iptoasn.com/data/ip2asn-combined.tsv.gz from https://iptoasn.com is a
# useful dataset for enrichment
asn_tsv_path = "ignored/ip2asn-combined.tsv"

[output]
# The format to use for stdout output. Can be "Json" or "PlainText".
format = "PlainText"
# slack = { webhook_url = "https://hooks.slack.com/services/..." }

[deduplication]
cache_size = 100000
cache_ttl_seconds = 3600
