# example certwatch.toml configuration 

# Valid levels: debug, info, warn, error
log_level = "info"

# The number of concurrent domain processing tasks.
# If commented out, defaults to (number of CPU cores).
# concurrency = 16

[metrics]
log_metrics = true
log_aggregation_seconds = 10

[performance]
queue_capacity = 100000

[network]
# REQUIRED: A running certstream-server certstream_url. Use
# https://github.com/CaliDog/certstream-server or similar.
certstream_url = "wss://127.0.0.1:8181/domains-only"
sample_rate = 0.01 # 1.0 = 100% sampling, 0.01 = 1% sampling
allow_invalid_certs = true

[matching]
# REQUIRED: A list of file paths containing regex patterns. For example:
pattern_files = ["data/patterns/match-all.txt"]

[dns]
# Optional: Specify a custom DNS resolver. If commented out, uses the system default.
resolver = "8.8.8.8:53"

# Optional: Specify the timeout for a single DNS query in milliseconds.
# timeout_ms = 5000

# DNS retry and backoff settings.
standard_retries = 3
standard_initial_backoff_ms = 500
nxdomain_retries = 5
nxdomain_initial_backoff_ms = 10000

[dns.health]
# The failure rate threshold to trigger the unhealthy state (e.g., 0.95 for 95%).
failure_threshold = 0.95
# The time window in seconds to consider for the failure rate calculation.
window_seconds = 120
# A known-good domain to resolve to check for recovery.
recovery_check_domain = "google.com"

[enrichment]
# REQUIRED: Path to the TSV ASN database file.
# The file must be tab-separated with 5 columns:
# CIDR, AS_Number, AS_Name, Country_Code, Description
# The https://iptoasn.com/data/ip2asn-combined.tsv.gz from https://iptoasn.com is a
# compatible dataset for enrichment
asn_tsv_path = "enrichment/ip2asn-combined.tsv"

[output]
# The format to use for stdout output. Can be "Json" or "PlainText".
format = "PlainText"

# Optional: webhooks
# [output.slack]
# webhook_url = "https://hooks.slack.com/services/..."
#
# The maximum number of alerts to batch together before sending.
# Defaults to 50.
# batch_size = 50
#
# The maximum time in seconds to wait before sending a batch, even if it's not full.
# Defaults to 300.
# batch_timeout_seconds = 300

[deduplication]
cache_size = 100000
cache_ttl_seconds = 3600
